parameters:
#    greibit_panel_admin.example.class: Greibit\PanelAdminBundle\Example

services:
#    greibit_panel_admin.example:
#        class: %greibit_panel_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
